import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {run} from '../lib/audit.js';
import {onRequest} from '../functions/api/run.js';
function setup(costTable=true){const raw=new DatabaseSync(':memory:');raw.exec(readFileSync(new URL('../migrations/0001_free_reservations.sql',import.meta.url),'utf8'));if(costTable)raw.exec(readFileSync(new URL('../migrations/0002_free_costs.sql',import.meta.url),'utf8'));const prepare=(sql,args=[])=>({bind(...v){return prepare(sql,v);},async run(){return {meta:{changes:Number(raw.prepare(sql).run(...args).changes)}};},async first(){return raw.prepare(sql).get(...args);}});return {raw,db:{prepare}};}
const request=(host='audit.broadcastwell.com')=>new Request('https://'+host+'/api/run',{method:'POST',headers:{'content-type':'application/json','cf-connecting-ip':'192.0.2.1'},body:JSON.stringify({category:'procurement software',company:'kalvenor.example',email:'kalvenor-preview@example.com'})});
const result=()=>({named:0,asked:10,tier:'named 0 of 10',chapter:'/category-door/',engine:'Perplexity',execution_id:'12345',cost:{currency:'USD',source:'provider_usage',requests:10,actual_usd:.081,prompt_tokens:2000,completion_tokens:1000},questions:Array.from({length:10},(_,i)=>({question:'Question '+i,status:'not named',answer:'Example vendor.',alternatives:['Example'],sources:['https://example.com/source']}))});
test('record actual provider cost and preserve complete evidence without persisting contact or answer data',async()=>{const s=setup(),old=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify(result()));try{const response=await run(request(),{LIMITS_DB:s.db,UPSTREAM_URL:'https://upstream.invalid',UPSTREAM_TOKEN:'synthetic'});assert.equal(response.status,200);const body=await response.json();assert.equal(body.questions.length,10);assert.equal(body.cost.actual_usd,.081);const row=s.raw.prepare('SELECT * FROM free_check_costs').get();assert.equal(row.actual_usd,.081);assert.equal(row.execution_id,'12345');assert.equal(row.status,'complete');assert.ok(!JSON.stringify(row).includes('@'));assert.ok(!JSON.stringify(row).includes('Example vendor'));}finally{globalThis.fetch=old;s.raw.close();}});
test('missing cost table fails before any paid request',async()=>{const s=setup(false),old=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;throw Error('must not call');};try{assert.equal((await run(request(),{LIMITS_DB:s.db})).status,503);assert.equal(calls,0);}finally{globalThis.fetch=old;s.raw.close();}});
test('failed upstream retains known cost and unknown total',async()=>{const s=setup(),old=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify({execution_id:'12346',cost:{currency:'USD',source:'provider_usage',requests:10,actual_usd:null,known_usd:.05}}),{status:502});try{assert.equal((await run(request(),{LIMITS_DB:s.db,UPSTREAM_URL:'https://upstream.invalid'})).status,502);const row=s.raw.prepare('SELECT * FROM free_check_costs').get();assert.equal(row.status,'failed');assert.equal(row.actual_usd,null);assert.equal(row.known_usd,.05);}finally{globalThis.fetch=old;s.raw.close();}});
test('preview requires explicit activation, isolated DB and exact synthetic sample',async()=>{const host='phase1-free-evidence-2026-09-14.absence-mini-audit.pages.dev',s=setup(),old=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;return new Response(JSON.stringify(result()));};try{assert.equal((await onRequest({request:request(host),env:{LIMITS_DB:s.db}})).status,503);const wrong=new Request('https://'+host+'/api/run',{method:'POST',body:JSON.stringify({company:'real.example'})});assert.equal((await onRequest({request:wrong,env:{LIMITS_DB:s.db,FREE_CHECK_PREVIEW:'true'}})).status,403);assert.equal(calls,0);assert.equal((await onRequest({request:request(host),env:{LIMITS_DB:s.db,FREE_CHECK_PREVIEW:'true',UPSTREAM_URL:'https://upstream.invalid'}})).status,200);assert.equal(calls,1);}finally{globalThis.fetch=old;s.raw.close();}});
