import {test} from 'node:test';
import assert from 'node:assert/strict';
import {run} from '../lib/audit.js';
import {onRequest} from '../functions/api/run.js';
test('unapproved preview hosts never touch production counters or the paid engine',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>{throw Error('must not call upstream');};try{const response=await onRequest({request:new Request('https://unapproved.absence-mini-audit.pages.dev/api/run',{method:'POST'}),env:new Proxy({},{get(){throw Error('must not read a binding');}})});assert.equal(response.status,503);assert.equal((await response.json()).message,'This check is awaiting activation.');}finally{globalThis.fetch=old;}});
function environment(){const values=new Map();return {AUDIT:{async get(k,type){const v=values.get(k);return type==='json'?v?JSON.parse(v):null:v;},async put(k,v){values.set(k,v);}},UPSTREAM_URL:'https://upstream.invalid/run',UPSTREAM_TOKEN:'synthetic-only'};}
const request=()=>new Request('https://preview.example/api/run',{method:'POST',headers:{'content-type':'application/json','cf-connecting-ip':'192.0.2.1'},body:JSON.stringify({category:'CRM',company:'Synthetic',email:'synthetic@example.test'})});
const result=()=>({named:0,asked:10,tier:'named 0 of 10',chapter:'/category-door/',engine:'Perplexity',questions:Array.from({length:10},(_,i)=>({question:'Synthetic question '+(i+1),status:'not named',answer:'Recorded synthetic answer. '.repeat(40),alternatives:Array.from({length:40},(_,n)=>'Synthetic alternative '+n),sources:Array.from({length:40},(_,n)=>'https://evidence.example/page/'+n),internal_key:'never disclose'}))});
test('full recorded answers, alternatives and page sources survive the narrow public contract',async()=>{const old=globalThis.fetch,value=result();globalThis.fetch=async()=>new Response(JSON.stringify(value));try{const response=await run(request(),environment());assert.equal(response.status,200);const body=await response.json();assert.equal(body.questions[0].answer,value.questions[0].answer);assert.equal(body.questions[0].alternatives.length,40);assert.equal(body.questions[0].sources.length,40);assert.equal(body.questions[0].source_urls_omitted,0);assert.ok(!JSON.stringify(body).includes('internal_key'));}finally{globalThis.fetch=old;}});
test('unsafe links are omitted explicitly and oversized evidence cannot appear complete',async()=>{const old=globalThis.fetch,value=result();value.questions[0].sources.push('javascript:alert(1)','https://user:password@evidence.example');globalThis.fetch=async()=>new Response(JSON.stringify(value));try{let body=await (await run(request(),environment())).json();assert.equal(body.questions[0].sources.length,40);assert.equal(body.questions[0].source_urls_omitted,2);value.questions[0].answer='x'.repeat(20001);body=await (await run(request(),environment())).json();assert.deepEqual(body.questions,[]);}finally{globalThis.fetch=old;}});
