import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {reserveFreeCheck} from '../lib/reservations.js';
import {onRequest} from '../functions/api/run.js';
import {run} from '../lib/audit.js';
function setup(){const raw=new DatabaseSync(':memory:');raw.exec(readFileSync(new URL('../migrations/0001_free_reservations.sql',import.meta.url),'utf8'));raw.exec(readFileSync(new URL('../migrations/0002_free_costs.sql',import.meta.url),'utf8'));const prepare=(sql,args=[])=>({bind(...v){return prepare(sql,v);},async run(){return {meta:{changes:Number(raw.prepare(sql).run(...args).changes)}};},async first(){return raw.prepare(sql).get(...args);}});return {raw,db:{prepare}};}
const now=Date.UTC(2026,8,14,12),base={day:'2026-09-14',now};
test('atomic reservation enforces a shared 100 cap under concurrent unique requests',async()=>{const s=setup();try{const values=await Promise.all(Array.from({length:125},(_,i)=>reserveFreeCheck(s.db,{...base,email:'synthetic'+i+'@example.test',ip:'192.0.2.'+i})));assert.equal(values.filter(v=>v.allowed).length,100);assert.equal(s.raw.prepare('SELECT count(*) n FROM free_check_reservations').get().n,100);assert.ok(!JSON.stringify(s.raw.prepare('SELECT * FROM free_check_reservations').all()).includes('@example.test'));}finally{s.raw.close();}});
test('one address and three network reservations cannot race past their caps',async()=>{const s=setup();try{const same=await Promise.all(Array.from({length:10},(_,i)=>reserveFreeCheck(s.db,{...base,email:'same@example.test',ip:'192.0.2.'+i})));assert.equal(same.filter(v=>v.allowed).length,1);const network=await Promise.all(Array.from({length:10},(_,i)=>reserveFreeCheck(s.db,{...base,email:'network'+i+'@example.test',ip:'198.51.100.1'})));assert.equal(network.filter(v=>v.allowed).length,3);}finally{s.raw.close();}});
test('Pages fails closed without atomic storage and failed provider requests retain reservations',async()=>{assert.equal((await onRequest({request:new Request('https://audit.broadcastwell.com/api/run',{method:'POST'}),env:{}})).status,503);const s=setup(),old=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;throw Error('synthetic network failure');};try{const request=()=>new Request('https://audit.broadcastwell.com/api/run',{method:'POST',headers:{'content-type':'application/json','cf-connecting-ip':'192.0.2.1'},body:JSON.stringify({category:'CRM',company:'Synthetic',email:'synthetic@example.test'})});const env={LIMITS_DB:s.db,UPSTREAM_URL:'https://upstream.invalid',UPSTREAM_TOKEN:'synthetic-only'};assert.equal((await run(request(),env)).status,502);assert.equal((await run(request(),env)).status,429);assert.equal(calls,1);assert.equal(s.raw.prepare('SELECT count(*) n FROM free_check_reservations').get().n,1);}finally{globalThis.fetch=old;s.raw.close();}});
