// Generated by scripts/build-page.mjs from the "/*" block of public/_headers. Do not edit.
// A page served by a function carries these, exactly as the static page does.
export const PAGE_HEADERS = {
  "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
  "Content-Security-Policy": "default-src 'none'; script-src 'sha256-IlWgEJ//sBXtGLXSaRr8rpqnqZP5LlDUO6BSeae//zw='; style-src 'self' 'sha256-YOkNeYyCseWH93WGPkFbk34r/kvkhXVikKP0r5as68g=' 'sha256-7N3Rbo/cV2nIFxwN2KqGWQs18yi890aJoN+COVpucAA='; font-src 'self'; img-src 'self' data: blob: https://framerusercontent.com; connect-src 'self'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'; upgrade-insecure-requests",
  "X-Frame-Options": "DENY",
  "X-Content-Type-Options": "nosniff",
  "Referrer-Policy": "strict-origin-when-cross-origin",
};
