/**
 * Keeps the page, its headers and the wheel module in step. Run after any edit to
 * public/index.html, public/assets/wheel.js or public/_headers:
 *
 *   node scripts/build-page.mjs
 *
 * 1. Copies public/assets/wheel.js into the page's one inline script, between the
 *    "wheel module: begin" and "wheel module: end" markers. The page stays one document
 *    with one hashed script, and the module file stays the portable copy other surfaces load.
 * 2. Recomputes the sha256 hashes of the inline script and the inline style block and
 *    writes them into the Content-Security-Policy line in public/_headers.
 * 3. Writes public/assets/fonts/inter-embed.css, the one font rule exported images embed,
 *    and adds its hash to style-src: some browsers hold an SVG image's own stylesheet to the
 *    page's policy, and the hash allows exactly that rule and nothing else.
 * 4. Writes lib/headers.js from the "/*" block of public/_headers, so a page served by a
 *    function (a result link) carries exactly the headers a static page does.
 *
 * `npm test` fails if any of the three has drifted, so a forgotten run cannot ship.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";

const path = (p) => fileURLToPath(new URL("../" + p, import.meta.url));
const BEGIN = "/* wheel module: begin */";
const END = "/* wheel module: end */";

let page = readFileSync(path("public/index.html"), "utf8");
const wheel = readFileSync(path("public/assets/wheel.js"), "utf8").trim();
const at = page.indexOf(BEGIN);
const end = page.indexOf(END);
if (at < 0 || end < at) throw new Error("the wheel markers are missing from public/index.html");
page = page.slice(0, at + BEGIN.length) + "\n" + wheel + "\n" + page.slice(end);
writeFileSync(path("public/index.html"), page);

function inline(tag) {
  const open = page.indexOf("<" + tag + ">");
  const body = page.indexOf(">", open) + 1;
  return page.slice(body, page.indexOf("</" + tag + ">", body));
}
const hash = (text) => "'sha256-" + createHash("sha256").update(text, "utf8").digest("base64") + "'";

const face = "@font-face{font-family:Inter;font-style:normal;font-weight:400 800;src:url(data:font/woff2;base64," + readFileSync(path("public/assets/fonts/inter-latin-var.woff2")).toString("base64") + ") format('woff2')}";
writeFileSync(path("public/assets/fonts/inter-embed.css"), face);

let headers = readFileSync(path("public/_headers"), "utf8");
headers = headers.replace(/script-src '[^']+'/, "script-src " + hash(inline("script")));
headers = headers.replace(/style-src 'self' '[^']+'( '[^']+')?/, "style-src 'self' " + hash(inline("style")) + " " + hash(face));
headers = headers.replace(/default-src 'none'; style-src '[^']+'; font-src data:/, "default-src 'none'; style-src " + hash(face) + "; font-src data:");
writeFileSync(path("public/_headers"), headers);

const start = headers.indexOf("/*\n");
const next = headers.slice(start + 3).search(/^\//m);
const block = next === -1 ? headers.slice(start) : headers.slice(start, start + 3 + next);
const pairs = block.split("\n").slice(1).map((line) => line.trim()).filter((line) => line && !line.startsWith("#") && line.includes(":")).map((line) => [line.slice(0, line.indexOf(":")).trim(), line.slice(line.indexOf(":") + 1).trim()]);
const lines = pairs.map(([name, value]) => "  " + JSON.stringify(name) + ": " + JSON.stringify(value) + ",");
writeFileSync(path("lib/headers.js"), "// Generated by scripts/build-page.mjs from the \"/*\" block of public/_headers. Do not edit.\n// A page served by a function carries these, exactly as the static page does.\nexport const PAGE_HEADERS = {\n" + lines.join("\n") + "\n};\n");
console.log("page, headers and lib/headers.js are in step");
